# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{zmb}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["kylef"]
  s.date = %q{2010-03-05}
  s.default_executable = %q{zmb}
  s.description = %q{ZMB, messenger bot}
  s.email = %q{inbox@kylefuller.co.uk}
  s.executables = ["zmb"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "bin/zmb",
     "lib/zmb.rb",
     "lib/zmb/event.rb",
     "lib/zmb/plugin.rb",
     "lib/zmb/settings.rb",
     "lib/zmb/timer.rb",
     "plugins/announce.rb",
     "plugins/autorejoin.rb",
     "plugins/bank.rb",
     "plugins/commands.rb",
     "plugins/dns.rb",
     "plugins/idle.rb",
     "plugins/irc.rb",
     "plugins/log.rb",
     "plugins/nickserv.rb",
     "plugins/poll.rb",
     "plugins/quote.rb",
     "plugins/relay.rb",
     "plugins/security.rb",
     "plugins/system.rb",
     "plugins/url.rb",
     "plugins/usermodes.rb",
     "plugins/users.rb",
     "test/helper.rb",
     "test/test_zmb.rb",
     "zmb.gemspec"
  ]
  s.homepage = %q{http://github.com/kylef/zmb}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{ZMB, messenger bot}
  s.test_files = [
    "test/helper.rb",
     "test/test_zmb.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_runtime_dependency(%q<json>, [">= 1.0.0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<json>, [">= 1.0.0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<json>, [">= 1.0.0"])
  end
end

